### ISSUE TITLE
cache corp IndustryJobs

### ISSUE THREAD

**Issue by RapidFiring** [RapidFiring/kwevebot#10]
Industry Jobs cachen
- Sortiert nach station/creator/startDate/finishDate

**Comment by Dream-Work** [comment]
all industry jobs are fetch and cached every 6 hours,

this is what we cached:

{
    "_id" : ObjectId("58590ba49240eb80c49b9fbe"),
    "jobID" : "313548067",
    "__v" : 0,
    "installerID" : "94081966",
    "installerName" : "Dom Oramara",
    "facilityID" : "1022322801110",
    "solarSystemID" : "30001225",
    "solarSystemName" : "JA-O6J",
    "stationID" : "1022322801110",
    "activityID" : 4,
    "blueprintID" : "1022560161399",
    "blueprintTypeID" : "968",
    "blueprintTypeName" : "Moa Blueprint",
    "blueprintLocationID" : "1022322801110",
    "outputLocationID" : "1022322801110",
    "runs" : "6",
    "cost" : "620786.00",
    "teamID" : "0",
    "licensedRuns" : "10",
    "probability" : "1",
    "productTypeID" : "968",
    "productTypeName" : "Moa Blueprint",
    "status" : "1",
    "timeInSeconds" : 498828,
    "startDate" : "2016-12-19 17:03:52",
    "endDate" : "2016-12-25 11:37:40",
    "completedDate" : "0001-01-01 00:00:00",
    "completedCharacterID" : "0",
    "successfulRuns" : 0,
    "startDateInt" : 1482163432,
    "endDateInt" : 1482662260
}
